/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#dce2f3",
              "outline": "#727876",
              "on-secondary-container": "#626566",
              "tertiary-container": "#242b37",
              "tertiary": "#0f1722",
              "secondary-fixed": "#e1e3e4",
              "on-secondary-fixed-variant": "#454748",
              "error-container": "#ffdad6",
              "surface-container-high": "#e1e8fd",
              "on-surface": "#141b2b",
              "tertiary-fixed-dim": "#c0c7d6",
              "surface-container-low": "#f1f3ff",
              "surface-bright": "#f9f9ff",
              "inverse-on-surface": "#edf0ff",
              "surface-variant": "#dce2f7",
              "on-tertiary-fixed": "#151c27",
              "secondary-container": "#e1e3e4",
              "on-secondary": "#ffffff",
              "outline-variant": "#c2c8c5",
              "on-tertiary-fixed-variant": "#404754",
              "on-secondary-fixed": "#191c1d",
              "inverse-surface": "#293040",
              "surface-tint": "#4d635e",
              "on-error-container": "#93000a",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed-variant": "#364b46",
              "primary-container": "#1a2f2b",
              "surface": "#f9f9ff",
              "secondary": "#5c5f60",
              "surface-container-highest": "#dce2f7",
              "on-primary-fixed": "#091f1b",
              "on-primary-container": "#809792",
              "on-surface-variant": "#424846",
              "on-error": "#ffffff",
              "primary": "#051a17",
              "primary-fixed-dim": "#b4ccc5",
              "on-tertiary-container": "#8b92a1",
              "on-background": "#141b2b",
              "primary-fixed": "#d0e8e1",
              "background": "#f9f9ff",
              "surface-dim": "#d3daef",
              "inverse-primary": "#b4ccc5",
              "error": "#ba1a1a",
              "surface-container": "#e9edff",
              "secondary-fixed-dim": "#c5c7c8",
              "on-primary": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "stack-lg": "24px",
              "container-max": "1280px",
              "section-gap": "120px",
              "margin-mobile": "20px",
              "gutter": "32px",
              "stack-sm": "8px",
              "stack-md": "16px",
              "margin-desktop": "64px"
      },
      "fontFamily": {
              "headline-xl": ["Epilogue"],
              "label-md": ["Inter"],
              "headline-lg": ["Epilogue"],
              "headline-xl-mobile": ["Epilogue"],
              "headline-md": ["Epilogue"],
              "body-md": ["Inter"],
              "caption": ["Inter"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "headline-xl": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-xl-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
}
